import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))

system_message = """
You are Entropo, a MEET entrepreneurship advisor..

Your job is to help students with their MEET entrepreneurship project-related questions and provide guidance in 
the topic Entrepreneurship like problem/solution fit, customer discovery, value proposition, business model canvas, market research, pitching,un fair advantge , MVP , UVP.

Rules:
- Always try to teach the user something new and provide them with resources to learn more.
- Always answer in a optimistic and encouraging tone.
- Never Answer with answers that are not true or that you are not sure about without telling the user to check them and put your resources .
- don't write the student's business plan/pitch for them (guide, don't do the work).
- don't guarantee funding or business success or any specific outcome.

Response format:
- one sentence repeating what the user asked
- the main answer
- one concrete action the user can take.

IMOPRTANT values
-embrace teamwork
-lead by example
-strive for exellence
-act with integrity
-treat everyone with respect and equality
-think big

"""


def run_chat():

    
    history = []
    goal=input("What is your goal for this chat? ")
    print("how can I help you with your goal ? ")
    # bonous 1
    dynamic_system_message = system_message + f"\n\nThe user's specific goal for this session is: {goal}"
    while True:
        
        
        user_input = input('>> ')

        if user_input.lower() == 'exit':
            break

        # type "save: <topic>" to save ONLY that specific answer as its own PDF
        # example: save: explain the business model canvas
        if user_input.lower().startswith('save'):
            # user_input[5:] cuts off the first 5 characters ("save:"), leaving just the topic
            # .strip() removes any leading/trailing spaces the user typed
            topic = user_input[5:].strip()

            if not topic:
                print('Please tell me what to save, e.g. "save: explain customer discovery"')
                continue

            # Ask Claude to answer just this ONE question, separate from the ongoing chat history,
            # so nothing else from the conversation ends up in the PDF.
            response = client.messages.create(
                model='claude-haiku-4-5-20251001',
                max_tokens=300,
                temperature=1,
                system=dynamic_system_message,
                messages=[{'role': 'user', 'content': topic}]  # only this one message
            )
            content_to_save = response.content[0].text

            path = save_specific_content_to_pdf(title=topic, content=content_to_save)
            print(f'Saved to {path}')

            # continue skips adding this to `history`, so it won't affect the main conversation
            continue


        history.append({'role': 'user', 'content': user_input})
        #the massages will be 6 ,3 for the user and 3 for the assistant
        # the API  needs to know the history each time cause it doesn't remember the previous messages so you need to send the history each time you send a new message
        response = client.messages.create(
            model='claude-haiku-4-5-20251001',
            max_tokens=300,
            # when i changed the max tokens to 50 the massge was cut off and it was not able to answer the question fully so i think it is the limit of the tokens that can be used in a single message
            temperature=1,
            #when I changed the temperature to 0 the response was completly identical , while at 1 it was more different wording structure... 
            #I think it is for controling the creativity of the response
            system=dynamic_system_message, 
            messages=history
        )

        reply = response.content[0].text
        
        # usage.input_tokens: The total count of tokens sent to Claude
        #usage.output_tokens: The count of tokens generated by Claude in its response message.
        #bonus 1
        print(f'Input Tokens: {response.usage.input_tokens}' , f'Output Tokens: {response.usage.output_tokens}')
        print(f'Entropo: {reply}')
        

        history.append({'role': 'assistant', 'content': reply})


def save_specific_content_to_pdf(title, content):
    """
    Saves ONE specific title + content into its own PDF file.
    Each save gets its own filename (based on the title) so files don't overwrite each other.
    """
    # Build a safe filename from the title:
    # - lowercase it
    # - keep only letters, numbers, and spaces (drops ?, !, etc. that aren't allowed in filenames)
    # - replace spaces with underscores
    safe_title = "".join(c if c.isalnum() or c == " " else "" for c in title.lower())
    safe_filename = safe_title.strip().replace(" ", "_")[:50]  # limit length so filename isn't huge

    if not safe_filename:
        safe_filename = "entropo_note"

    output_path = f"output/{safe_filename}.pdf"
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=1*inch, bottomMargin=1*inch)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 0.3*inch))

    # Escape < and > so Claude's answer can't accidentally break the PDF layout
    # (Paragraph treats these as HTML-like tags)
    safe_content = content.replace("<", "&lt;").replace(">", "&gt;")

    # Split on blank lines so multi-paragraph answers get proper spacing between paragraphs
    for paragraph in safe_content.split("\n\n"):
        if paragraph.strip():
            story.append(Paragraph(paragraph.strip(), styles["Normal"]))
            story.append(Spacer(1, 0.15*inch))

    doc.build(story)
    return os.path.abspath(output_path)


def get_reply(user_input, history, system_message):
    history.append({'role': 'user', 'content': user_input})

    response = client.messages.create(
        model='claude-haiku-4-5-20251001',
        max_tokens=300,
        temperature=1,
        system=system_message,
        messages=history
    )

    reply = response.content[0].text
    history.append({'role': 'assistant', 'content': reply})
    return reply



























#Lab3: the chatbot works exactly how it should and it is remember the history
#PA : I think the culture and beliefs represent the invisable rules that we work based on it and it shape our life and the way we think
#if i delete : 1)system=system_message: the Ai will not know what it should do and it will not be able to answer the questions correctly and it will not be able to follow the rules that are set for it and it will not be able to provide the resources for the user to learn more and it will not be able to answer in an optimistic and encouraging tone.
#2) Never Answer with answers that are not true or that you are not sure about without telling the user to check them and put your resources .: the Ai will not be able to provide the resources for the user to learn more and it will not be able to answer in an optimistic and encouraging tone.
#3)- End with one follow-up question.: the Ai will not be able to ask the user a follow-up question and it will not be able to keep the conversation going so the users may get confused.
#bug diary : when starting doing the bouns 1 i was getting an error that the system message is not defined and i realized that it is because i defined the system message inside the run_chat function and i was trying to use it outside the function so i moved the system message definition outside the function and it worked fine




#Lab 2 reflection:
#PA : maybe like Utiilty Meters like electricity and water that the more you use, the more you pay.
# if I delete..: 1) history.append({'role': 'user', 'content': user_input}) : the Ai won't remember any of the previous conversations if you don't store the history of the conversation and for the input_tokens it will be less because the input will be less.
#2)history.append({'role': 'assistant', 'content': reply}): the Ai won't remember any of the previous conversations if you don't store the history and for the output_tokens it will be less because the output will be less. 
#3)print('History so far:', history) : yes the AI will not remember any of the previous conversations
# I didn't have any bug this lab .




#Lab 1 reflection:
#chat gpt you talk to the website UI but here you talk directly to the backend .
#Reflection: 
#1.when you go to new place like a country or a new workplace you need to give them your CV or applying for a visa or a passport
#2.1) history.append({'role': 'assistant', 'content': reply}) : the Ai won't remember any of the previous conversations if you don't store the history of the conversation.
#2)load_dotenv(): i think it would start but won't reach the API key cuz its in .env and it needs to be loaded 
#3) temperature=0.7: i think its for controling the speed of response and it won't be a visible change
#3. first I thougth it was the API key fault but then i realized that it was the terminal it needed a virtual enviromment in a certain way  i think there is a vere huge gape between them #your python code here!
